# Generated by Django 4.0.3 on 2022-03-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitvapi', '0002_alter_workout_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='exercise_id',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='workout_id',
            new_name='workout',
        ),
    ]
