# Generated by Django 4.0.3 on 2022-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitvapi', '0003_rename_category_id_exercise_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='', height_field=400, upload_to='', width_field=300),
            preserve_default=False,
        ),
    ]
